### PR TITLE
Migrating to null safety

### PR DESCRIPTION
**Pull request by shinayser**
Migrating the library to null safety.

### CODE REVIEW

**Comment by Arcturus5404** [comment]
Please merge this PR and publish to pub.dev!

**Comment by MichaelFenwick** [comment]
Thanks so much for the PR. Alongside the update to null safety, I noticed you also decided to take some time to update the project to more current code style conventions (a lack of the `new` keyword, removing constructor argument type hints, etc.). I'd rather these changes be separate, and also wanted to get the project fully converted to the pedantic code style. I've already done the code style changes, and am now working on the null aware changes, after which (probably later tonight) I'll publish the new version to pub.dev. As I'm making these changes, I've been using your PR as a guide, so thanks again for this submission!

**Comment by shinayser** [comment]
@MichaelFenwick feel free to change whatever you need! 😉

**Comment by MichaelFenwick** [comment]
I've pushed and published the changes to https://pub.dev/packages/color, and the latest version of the project is now null safe. Closing this PR as its goal has been accomplished.

**Pull request closed without merging**
